[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

[template.environment]
  PASSWORD_SECRET = "bcrypted password"
  PRIVATE_KEY = "RSA Private Key"
  PUBLIC_KEY = "RSA Public Key"
